/*****************************************************************************
Copyright: 2016-2020, Artosyn. Co., Ltd.
File name: hal_spi.c
Description: The external HAL APIs to use the SPI controller.
Author: Artosyn Software Team
Version: 0.0.1
Date: 2016/12/20
History: 
        0.0.1    2016/12/20    The initial version of hal_spi.c
*****************************************************************************/

#include "hal_spi.h"
#include "debuglog.h"

/**
* @brief  The SPI initialization function which must be called 
*         before using the SPI controller.
* @param  e_spiComponent    The SPI controller number, the right number 
*                           should be 0-7 and totally 8 SPI controllers 
*                           can be used by application.
*         pst_spiInitInfo   spi init info,the member's value should use 
*                           the enum value.
* @retval HAL_OK            means the initializtion is well done.
*         HAL_SPI_ERR_INIT  means some error happens in the initializtion.
* @note   None.
*       
*/
HAL_RET_T HAL_SPI_MasterInit(ENUM_HAL_SPI_COMPONENT e_spiComponent, 
                             STRU_HAL_SPI_INIT *pst_spiInitInfo)
{
    uint16_t u16_spiDivision;
    // init default value.
    STRU_SPI_InitTypes st_spiInit = 
    {
        .ctrl0   = 0x47,
        .clk_Mhz = 0x09,
        .Tx_Fthr = 0x03,
        .Rx_Ftlr = 0x6,
        .SER     = 0x01
    };
   
    if (e_spiComponent > HAL_SPI_COMPONENT_7)
    {
        return HAL_SPI_ERR_INIT;
    }

    if (NULL == pst_spiInitInfo)
    {
        return HAL_SPI_ERR_INIT;
    }
   
    // BAUDR
    st_spiInit.clk_Mhz = pst_spiInitInfo->u16_halSpiBaudr;
    
    // SCPOL 
    st_spiInit.ctrl0 &= (~0x80);
    st_spiInit.ctrl0 |= (((uint16_t)(pst_spiInitInfo->e_halSpiPolarity)) << 7) & 0x80;

    // SCPH
    st_spiInit.ctrl0 &= (~0x40);
    st_spiInit.ctrl0 |= (((uint16_t)(pst_spiInitInfo->e_halSpiPhase)) << 6) & 0x40;
    
    SPI_master_init((ENUM_SPI_COMPONENT)(e_spiComponent), &st_spiInit);

    return HAL_OK;
}

/**
* @brief  The SPI data write function which can be used to send out SPI data 
*         by the SPI controller.
* @param  e_spiComponent          The SPI controller number, the right number 
*                                 should be 0-7 and totally 8 SPI controllers 
*                                 can be used by application.
*         pu8_wrData              The transmit buffer pointer to be sent out 
*                                 by SPI bus. 
*         u32_wrSize              The transmit buffer size in byte. 
*         pu8_rdData              The receive buffer pointer to hold the data 
*                                 in read operation.
*         u32_rdSize              The receive buffer size in byte.
* @retval HAL_OK                  means the SPI data write is well done.
*         HAL_SPI_ERR_WRITE_DATA  means some error happens in the SPI data write.
*         HAL_SPI_ERR_READ_DATA   means some error happens in the data read.
*         HAL_SPI_ERR_COMPONENT   means component error.
* @note   the SPI controller must work in master mode.
*         when read data,u32_wrSize must equal u32_rdSize,because the read data's
*         clock is generated by the master.
*         e.g peripheral chip's read process is:
*             1.master send identification.
*             2.master send address.
*             3.slave send data.
*         so the master must send 3 bytes(identification +  address + X,X can be 
*         any data). pu8_rdData receive 3 bytes,pu8_rdData[0] and pu8_rdData[1] 
*         is invalid data, pu8_rdData[2] is the real effective data.
*
*/
HAL_RET_T HAL_SPI_MasterWriteRead(ENUM_HAL_SPI_COMPONENT e_spiComponent, 
                                  uint8_t *pu8_wrData,
                                  uint32_t u32_wrSize,
                                  uint8_t *pu8_rdData,
                                  uint32_t u32_rdSize)
{
    if (e_spiComponent > HAL_SPI_COMPONENT_7)
    {
        return HAL_SPI_ERR_COMPONENT;
    }
    if ((u32_wrSize > 0) && (NULL == pu8_wrData))
    {
        return HAL_SPI_ERR_WRITE_DATA;
    }
    if ((u32_rdSize > 0) && (NULL == pu8_rdData))
    {
        return HAL_SPI_ERR_READ_DATA;
    }
    
    SPI_write_read((ENUM_SPI_COMPONENT)(e_spiComponent),
                    pu8_wrData,
                    u32_wrSize,
                    pu8_rdData,
                    u32_rdSize);
    return HAL_OK;
}


